steps:
  - id: test-api
    name: "gcr.io/cloud-builders/gcloud"
    waitFor:
      - "-"
    args:
      - builds
      - submit
      - api
      - --config=api/cloudbuild.yaml

  - id: test-front
    name: "gcr.io/cloud-builders/gcloud"
    waitFor:
      - "-"
    args:
      - builds
      - submit
      - front
      - --config=front/cloudbuild.yaml

timeout: 900s
