steps:
  - id: test-api
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    waitFor:
      - "-"
    args:
      - "-c"
      - |
        gcloud builds submit api --config=api/cloudbuild.yaml

  - id: test-front
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    waitFor:
      - "-"
    args:
      - "-c"
      - |
        gcloud builds submit front --config=front/cloudbuild.yaml

timeout: 900s
